# Generated by Django 2.0.3 on 2018-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.IntegerField()),
                ('sensorId', models.IntegerField()),
                ('sensorValue', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
