# Generated by Django 2.0.3 on 2018-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180325_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='roomNo',
            field=models.CharField(max_length=10),
        ),
    ]
